/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClassNumber = bigint;
export interface Content {
  'id' : ContentId,
  'title' : string,
  'classNumber' : ClassNumber,
  'contentType' : ContentType,
  'link' : string,
  'description' : string,
  'subjectId' : SubjectId,
}
export type ContentId = bigint;
export type ContentType = { 'pdfNotes' : null } |
  { 'quiz' : null } |
  { 'recordedClass' : null } |
  { 'liveClass' : null };
export interface Doubt {
  'id' : bigint,
  'classNumber' : ClassNumber,
  'subjectName' : string,
  'doubtText' : string,
  'subjectId' : SubjectId,
  'timestamp' : Time,
  'phone' : Phone,
  'reply' : [] | [string],
}
export type Phone = string;
export interface Question {
  'correctOption' : bigint,
  'text' : string,
  'options' : Array<string>,
}
export interface Quiz {
  'title' : string,
  'contentId' : ContentId,
  'questions' : Array<Question>,
}
export interface Student {
  'classNumber' : ClassNumber,
  'name' : string,
  'phone' : Phone,
}
export interface Subject {
  'id' : SubjectId,
  'classNumber' : ClassNumber,
  'name' : string,
}
export type SubjectId = bigint;
export type Time = bigint;
export interface UserProfile {
  'classNumber' : [] | [bigint],
  'name' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContent' : ActorMethod<
    [ClassNumber, SubjectId, ContentType, string, string, string],
    ContentId
  >,
  'addQuiz' : ActorMethod<[ContentId, string, Array<Question>], undefined>,
  'addSubject' : ActorMethod<[ClassNumber, string], SubjectId>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContent' : ActorMethod<[ContentId], undefined>,
  'deleteSubject' : ActorMethod<[SubjectId], undefined>,
  'getAllDoubts' : ActorMethod<[], Array<Doubt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<
    [ClassNumber, SubjectId, ContentType],
    Array<Content>
  >,
  'getMyDoubts' : ActorMethod<[Phone], Array<Doubt>>,
  'getQuiz' : ActorMethod<[ContentId], Quiz>,
  'getStudent' : ActorMethod<[Phone], Student>,
  'getSubjects' : ActorMethod<[ClassNumber], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudent' : ActorMethod<[Phone, ClassNumber], undefined>,
  'replyDoubt' : ActorMethod<[bigint, string], undefined>,
  'requestOtp' : ActorMethod<[Phone], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDoubt' : ActorMethod<
    [Phone, ClassNumber, SubjectId, string, string],
    undefined
  >,
  'updateStudentName' : ActorMethod<[Phone, string], undefined>,
  'verifyOtp' : ActorMethod<[Phone, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];