/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ClassNumber = IDL.Nat;
export const SubjectId = IDL.Nat;
export const ContentType = IDL.Variant({
  'pdfNotes' : IDL.Null,
  'quiz' : IDL.Null,
  'recordedClass' : IDL.Null,
  'liveClass' : IDL.Null,
});
export const ContentId = IDL.Nat;
export const Question = IDL.Record({
  'correctOption' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Phone = IDL.Text;
export const Doubt = IDL.Record({
  'id' : IDL.Nat,
  'classNumber' : ClassNumber,
  'subjectName' : IDL.Text,
  'doubtText' : IDL.Text,
  'subjectId' : SubjectId,
  'timestamp' : Time,
  'phone' : Phone,
  'reply' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'classNumber' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const Content = IDL.Record({
  'id' : ContentId,
  'title' : IDL.Text,
  'classNumber' : ClassNumber,
  'contentType' : ContentType,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : SubjectId,
});
export const Quiz = IDL.Record({
  'title' : IDL.Text,
  'contentId' : ContentId,
  'questions' : IDL.Vec(Question),
});
export const Student = IDL.Record({
  'classNumber' : ClassNumber,
  'name' : IDL.Text,
  'phone' : Phone,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'classNumber' : ClassNumber,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContent' : IDL.Func(
      [ClassNumber, SubjectId, ContentType, IDL.Text, IDL.Text, IDL.Text],
      [ContentId],
      [],
    ),
  'addQuiz' : IDL.Func([ContentId, IDL.Text, IDL.Vec(Question)], [], []),
  'addSubject' : IDL.Func([ClassNumber, IDL.Text], [SubjectId], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContent' : IDL.Func([ContentId], [], []),
  'deleteSubject' : IDL.Func([SubjectId], [], []),
  'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func(
      [ClassNumber, SubjectId, ContentType],
      [IDL.Vec(Content)],
      ['query'],
    ),
  'getMyDoubts' : IDL.Func([Phone], [IDL.Vec(Doubt)], ['query']),
  'getQuiz' : IDL.Func([ContentId], [Quiz], ['query']),
  'getStudent' : IDL.Func([Phone], [Student], ['query']),
  'getSubjects' : IDL.Func([ClassNumber], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func([Phone, ClassNumber], [], []),
  'replyDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestOtp' : IDL.Func([Phone], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDoubt' : IDL.Func(
      [Phone, ClassNumber, SubjectId, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateStudentName' : IDL.Func([Phone, IDL.Text], [], []),
  'verifyOtp' : IDL.Func([Phone, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ClassNumber = IDL.Nat;
  const SubjectId = IDL.Nat;
  const ContentType = IDL.Variant({
    'pdfNotes' : IDL.Null,
    'quiz' : IDL.Null,
    'recordedClass' : IDL.Null,
    'liveClass' : IDL.Null,
  });
  const ContentId = IDL.Nat;
  const Question = IDL.Record({
    'correctOption' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Phone = IDL.Text;
  const Doubt = IDL.Record({
    'id' : IDL.Nat,
    'classNumber' : ClassNumber,
    'subjectName' : IDL.Text,
    'doubtText' : IDL.Text,
    'subjectId' : SubjectId,
    'timestamp' : Time,
    'phone' : Phone,
    'reply' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'classNumber' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Content = IDL.Record({
    'id' : ContentId,
    'title' : IDL.Text,
    'classNumber' : ClassNumber,
    'contentType' : ContentType,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const Quiz = IDL.Record({
    'title' : IDL.Text,
    'contentId' : ContentId,
    'questions' : IDL.Vec(Question),
  });
  const Student = IDL.Record({
    'classNumber' : ClassNumber,
    'name' : IDL.Text,
    'phone' : Phone,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'classNumber' : ClassNumber,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContent' : IDL.Func(
        [ClassNumber, SubjectId, ContentType, IDL.Text, IDL.Text, IDL.Text],
        [ContentId],
        [],
      ),
    'addQuiz' : IDL.Func([ContentId, IDL.Text, IDL.Vec(Question)], [], []),
    'addSubject' : IDL.Func([ClassNumber, IDL.Text], [SubjectId], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContent' : IDL.Func([ContentId], [], []),
    'deleteSubject' : IDL.Func([SubjectId], [], []),
    'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func(
        [ClassNumber, SubjectId, ContentType],
        [IDL.Vec(Content)],
        ['query'],
      ),
    'getMyDoubts' : IDL.Func([Phone], [IDL.Vec(Doubt)], ['query']),
    'getQuiz' : IDL.Func([ContentId], [Quiz], ['query']),
    'getStudent' : IDL.Func([Phone], [Student], ['query']),
    'getSubjects' : IDL.Func([ClassNumber], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func([Phone, ClassNumber], [], []),
    'replyDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestOtp' : IDL.Func([Phone], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDoubt' : IDL.Func(
        [Phone, ClassNumber, SubjectId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateStudentName' : IDL.Func([Phone, IDL.Text], [], []),
    'verifyOtp' : IDL.Func([Phone, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };